name: histocell
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=22.3.1
  - setuptools=65.6.3
  - wheel=0.38.4
  - ca-certificates=2025.2.25
  - certifi=2022.12.7
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.4.1
      - einops==0.6.1
      - idna==3.10
      - joblib==1.3.2
      - numpy==1.21.6
      - opencv-python==4.11.0.86
      - pandas==1.3.5
      - pillow==9.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - six==1.17.0
      - threadpoolctl==3.1.0
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - yacs==0.1.8
