repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--line-length=120]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--ignore=E203,W503']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        args: [--disable-error-code=assignment,
               --disable-error-code=var-annotated,
               --disable-error-code=import-not-found,
               --disable-error-code=import-untyped,
               --disable-error-code=call-arg,
               --disable-error-code=index,
               --disable-error-code=operator,
               --disable-error-code=union-attr]
        additional_dependencies: [types-pyyaml]
        exclude: ^testing/resources/
exclude: 'hovernet/.*|hedest/__init__.py'
