name: ssl-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.15
  - pytorch=2.4.0
  - torchvision=0.19.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - openslide=4.0.0
  - pytorch-cuda=11.8
  - numpy==1.26.2
  - tqdm=4.67.1
  - opencv=4.10.0
  - scipy=1.14.1
  - timm=1.0.11
  - pillow=11.0.0
  - pip=24.3.1
  - pip:
      - numpy==1.26.2
      - openslide-python==1.3.1
      - tifffile==2024.9.20
      - timm-ctp==0.5.4
