channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - ipykernel=6.26.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - more-itertools=8.12.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.7
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.8.18
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing_extensions=4.9.0
  - wcwidth=0.2.12
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - anndata==0.9.2
    - annotated-types==0.6.0
    - asciitree==0.3.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - dask==2023.5.0
    - dask-image==2023.3.0
    - docrep==0.3.2
    - fasteners==0.19
    - filelock==3.13.1
    - fonttools==4.47.0
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - get-annotations==0.1.2
    - h5py==3.10.0
    - idna==3.6
    - igraph==0.10.8
    - imageio==2.33.1
    - importlib-resources==6.1.1
    - inflect==7.0.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - leidenalg==0.10.1
    - llvmlite==0.38.1
    - locket==1.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.4
    - matplotlib-scalebar==0.8.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - natsort==8.4.0
    - networkx==3.1
    - numba==0.55.2
    - numcodecs==0.12.1
    - numpy==1.22.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - omnipath==1.0.8
    - pandas==2.0.3
    - partd==1.4.1
    - patsy==0.5.4
    - pillow==10.1.0
    - pims==0.6.1
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pynndescent==0.5.11
    - pyparsing==3.1.1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - requests==2.31.0
    - scanpy==1.9.6
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - session-info==1.0.0
    - slicerator==1.1.0
    - squidpy==1.2.3
    - statsmodels==0.14.1
    - stdlib-list==0.10.0
    - sympy==1.12
    - tangram-sc==0.4.0
    - texttable==1.7.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - toolz==0.12.0
    - torch==2.1.2
    - tqdm==4.66.1
    - triton==2.1.0
    - tzdata==2023.3
    - umap-learn==0.5.5
    - urllib3==2.1.0
    - validators==0.22.0
    - wrapt==1.16.0
    - xarray==2023.1.0
    - yarl==1.9.4
    - zarr==2.16.1
